name: Package Desktop App

on: workflow_dispatch

jobs:
  package-windows-app:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main

    - uses: actions/setup-node@master
      with:
        node-version: "20"

    - name: Check Node Version
      run: node -v

    - name: See Directory
      run: ls

    - name: Install Dependencies
      run: npm install
    
    - name: Package Windows App
      run: npm run package

    - name: Archive Package Artifacts
      uses: actions/upload-artifact@master
      with:
        name: windows-package
        path: apps/desktop/out


  package-mac-app:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
        
    - uses: actions/setup-node@master
      with:
        node-version: "20"

    - name: Check Node Version
      run: node -v

    - name: See Directory
      run: ls

    - name: Install Dependencies
      run: npm install
    
    - name: Package MacOS App
      run: npm run package

    - name: Archive Package Artifacts
      uses: actions/upload-artifact@master
      with:
        name: macos-package
        path: apps/desktop/out
